name: Test

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      module_version:
        description: 'Module Version'
        required: true
        default: 'Latest'
      deploy:
        description: 'Deploy'
        required: true
        default: 'false'

jobs:
  Jazzy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: View context attributes
        uses: actions/github-script@v4
        id: set-release
        with:
          script: return context.payload.release.tag_name
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-release.outputs.result}}"
      - name: Deploy
        if : github.event_name == 'release' || github.event_name == 'workflow_dispatch' &&  github.event.inputs.deploy == 'true'
        run: echo "deploy"
      - name: Upload documentation as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: docs
